# Generated by Django 4.1.5 on 2024-08-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_is_active_appuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('relase_year', models.IntegerField()),
                ('loan_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('receivable', models.BooleanField(default=True)),
                ('borrower', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
